services:
  postgres:
    build: ./postgres
    container_name:  postgres
    env_file: .env
    restart: always
    networks:
      - transcendance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # To remove at the end (used to debug)

  redis: # for Django Channels (multiplayer) and caching
    image: redis:7.0
    container_name: redis
    networks:
      - transcendance
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    networks:
      - transcendance
    restart: always
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
      - blockchain

  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - transcendance
    restart: always
    ports:
      - "7443:443"
    volumes:
      - ./nginx/frontend:/usr/share/nginx/html
    depends_on:
      - backend

  blockchain:
    build: ./blockchain
    container_name: blockchain
    networks:
      - transcendance
    command:
      - "--dev"   # Development mode
      - "--datadir=/blockchain/data"
      - "--http"  # Http api
      - "--http.addr=0.0.0.0"
      - "--http.port=8545"
      - "--http.api=eth,web3,personal,net"
      - "--ipcpath=/tmp/geth.ipc"
    ports:
      - "8545:8545"
    volumes:
      - ./blockchain/data:/blockchain/data

networks:
  transcendance:
    driver: bridge

volumes:
  postgres_data:
